[reverse-proxy]
enabled = true
filter = reverse-proxy
backend = auto
logpath = /var/log/reverse-proxy/access.log
maxretry = 10
findtime = 60
bantime = 3600
ignoreip = 127.0.0.1/8 ::1 10.0.0.0/8

[reverse-proxy-4xx]
enabled = true
filter = reverse-proxy-4xx
backend = auto
logpath = /var/log/reverse-proxy/access.log
maxretry = 5
findtime = 10m
bantime = 1h
ignoreip = 127.0.0.1/8 ::1 10.0.0.0/8

[reverse-proxy-badbots]
enabled = true
filter = reverse-proxy-badbots
backend = auto
logpath = /var/log/reverse-proxy/access.log
maxretry = 5
findtime = 10m
bantime = 1h
ignoreip = 127.0.0.1/8 ::1 10.0.0.0/8