[Definition]
failregex = ^.*prefix="REQUEST" client_ip=<HOST> .* method=(GET|POST|HEAD|PUT|DELETE|PATCH) path=/\.(env|git|DS_Store|aws|config)[^ ]* status=\d+
            ^.*prefix="REQUEST" client_ip=<HOST> .* method=(PROPFIND|CONNECT) [^ ]* status=\d+
            ^.*prefix="REQUEST" client_ip=<HOST> .* method=(GET|POST|HEAD) path=/(<webmail>|<phpmyadmin>|<wordpress>|cgi-bin|mysqladmin|actuator|SDK|ecp|developmentserver|wp-admin|wp-login\.php|phpinfo|\.aws|\.ssh)[^ ]* status=(400|404|405|413)
            ^.*prefix="REQUEST" client_ip=<HOST> .* method=(GET|POST|HEAD) path=/[^ ]*[\x00-\x1f\x80-\xff]

webmail = roundcube|(ext)?mail|horde|(v-?)?webmail
phpmyadmin = (typo3/|xampp/|admin/|)(pma|(php)?[Mm]y[Aa]dmin)
wordpress = wp-(login|signup|admin)\.php

ignoreregex =

[Init]
maxlines = 1